local gt = this.getroottable();

if (!("Strings" in gt.Const))
{
	gt.Const.Strings <- {};
}

gt.Const.Strings.CharacterNames <- [
	"Sigurd",
	"Siegfried",
	"Hilmar",
	"Harald",
	"Sigbold",
	"Siegward",
	"Ulfert",
	"Kalle",
	"Espen",
	"Hagen",
	"Ewald",
	"Wenzel",
	"Ejnar",
	"Gunther",
	"Ivar",
	"Jannold",
	"Bertel",
	"Ingolf",
	"Wiedekind",
	"Egon",
	"Casimir",
	"Hilderich",
	"Friedrich",
	"Wendel",
	"Hasso",
	"Wilreich",
	"Hans",
	"Torhelm",
	"Fritz",
	"Mattis",
	"Birk",
	"Arnold",
	"Knut",
	"Adler",
	"Niels",
	"Elmer",
	"Ulfert",
	"Jost",
	"Tostig",
	"Bertram",
	"Albrecht",
	"Kunold",
	"Baldomar",
	"Dietmar",
	"Donbert",
	"Erwin",
	"Caspar",
	"Arne",
	"Edmund",
	"Kunibert",
	"Arnulf",
	"Eduard",
	"Meinolf",
	"Oskar",
	"Giselherr",
	"Reimar",
	"Wernhard",
	"Vander",
	"Werner",
	"Wigald",
	"Willibald",
	"Bjarne",
	"Henrik",
	"Ruthard",
	"Alrik",
	"Hubert",
	"Ernst",
	"Rudolf",
	"Hartbert",
	"Asgeir",
	"Horik",
	"Konrad",
	"Gerhard",
	"Hanke",
	"Guido",
	"Till",
	"Geralt",
	"Hartwig",
	"Thorben",
	"Gisbert",
	"Bruno",
	"Wigmar",
	"Gottfried",
	"Hakon",
	"Goswin",
	"Guntbert",
	"Eckbert",
	"Roger",
	"Gebhard",
	"Ralf",
	"Bernfried",
	"Guntram",
	"Ferdinand",
	"Leonhard",
	"Gerlach",
	"Helmer",
	"Gustav",
	"Gerold",
	"Gero",
	"Gerulf",
	"Emmerich",
	"Karl",
	"Dirk",
	"Falk",
	"Anselm",
	"Diethelm",
	"Alvar",
	"Eberecht",
	"Wilhelm",
	"Hildebert",
	"Erik",
	"Theudobald",
	"Havard",
	"Hakon",
	"Wolfgang",
	"Erling",
	"Kori",
	"Randolf",
	"Rollo",
	"Leif",
	"Lars",
	"Torsten",
	"Ingmar",
	"Asbjorn",
	"Steinar",
	"Reynhart",
	"Baldur",
	"Olaf",
	"Egil",
	"Magnus",
	"Gunnar",
	"Svein",
	"Carsten",
	"Eugen",
	"Anton",
	"Torvald",
	"Bernhard",
	"Einar",
	"Leberecht",
	"Ragnar",
	"Ottmar",
	"Otwin",
	"Balon",
	"Eberold",
	"Bertwin",
	"Oswald",
	"Rabe",
	"Reimund",
	"Wolf",
	"Eberhard",
	"Grimwald",
	"Hugo",
	"Hallstein",
	"Helfrich",
	"Haribert",
	"Balduin",
	"Waldemar",
	"Engelbert",
	"Tobjoern",
	"Erland",
	"Torkel",
	"Horst",
	"Thorismund",
	"Torleif",
	"Erhard",
	"Ulf",
	"Otto",
	"Hermann",
	"Heinrich",
	"Halsten",
	"Kettilmund",
	"Alfgeir",
	"Sorrel",
	"Hartmut",
	"Lothar",
	"Manfred",
	"Reinhold",
	"Alfred",
	"Dietrich",
	"Rupert",
	"Heimrad",
	"Sigmar",
	"Friso",
	"Landrich",
	"Lienhard",
	"Sigmund",
	"Reinhardt",
	"Kurt",
	"Bodo",
	"Volmar",
	"Liebwin",
	"Dieter",
	"Ulrich",
	"Eike",
	"Walram",
	"Malte",
	"Grimald",
	"Berthold",
	"Alberich",
	"Raban",
	"Rumold",
	"Witold",
	"Volker",
	"Volkhart",
	"Bertolf",
	"Walter",
	"Ortwin",
	"Humbert",
	"Adelmar",
	"Konrad",
	"Gernot",
	"Radulf",
	"Ludolf",
	"Giselher",
	"Adelbert",
	"Hjalmar",
	"Reiner",
	"Burkhard",
	"Winrich",
	"Wilderich",
	"Wilfried",
	"Robert",
	"Wolfram",
	"Raimund",
	"Thilmann",
	"Norman",
	"Ludger",
	"Alwin",
	"Markward",
	"Markolf",
	"Hadebrand",
	"Roderick",
	"Rambert",
	"Meinrad"
];
gt.Const.Strings.CharacterNamesFemale <- [
	"Ingrid",
	"Helga",
	"Irma",
	"Adela",
	"Birgit",
	"Bertha",
	"Borghild",
	"Brunhild",
	"Frida",
	"Gudrun",
	"Hilda",
	"Sigrid",
	"Mathilda",
	"Gerhild"
];
gt.Const.Strings.BarbarianNames <- [
	"Smud",
	"Hirguld",
	"Braum",
	"Grimner",
	"Harif",
	"Skallag",
	"Hylle",
	"Guder",
	"Asberk",
	"Iyrd",
	"Brand",
	"Obrun",
	"Jormal",
	"Joltul",
	"Jotnar",
	"Huggur",
	"Eirik",
	"Hafgufa",
	"Vaettir",
	"Frugar",
	"Lorki",
	"Rangvald",
	"Helheimer",
	"Brokkr",
	"Rork",
	"Hurik",
	"Skarbrand",
	"Sigbaal"
];
gt.Const.Strings.BarbarianTitles <- [
	"the Slayer",
	"the Destroyer",
	"the Ravager",
	"the Pillager",
	"the Conquerer",
	"the Slayer",
	"the Defiler",
	"the Despoiler",
	"the Menace",
	"the Headhunter",
	"the Ravager",
	"Skullcrusher",
	"Bonebreaker",
	"Slaughterborne",
	"the Chosen",
	"Battleborn",
	"Ironside",
	"the Bloodied",
	"the Beast",
	"Beastblood",
	"the Wolfclaw",
	"the Savage",
	"the Bloodletter",
	"the Crusher",
	"the Everlasting"
];
gt.Const.Strings.SouthernNames <- [
	"Jamil",
	"Uthman",
	"Sayid",
	"Radwan",
	"Yazid",
	"Sahir",
	"Wahib",
	"Amira",
	"Aslam",
	"Atiq",
	"Sadan",
	"Ayman",
	"Hakan",
	"Hafas",
	"Sawar",
	"Shuyab",
	"Husan",
	"Hamdun",
	"Ayshun",
	"Jabir",
	"Zuhri",
	"Jifri",
	"Galib",
	"Tamim",
	"Jaquba",
	"Zawahir",
	"Shurayd",
	"Walid",
	"Musa",
	"Ubaid",
	"Harad",
	"Tariq",
	"Wasi",
	"Fariss",
	"Abani",
	"Mutar",
	"Uthman",
	"Tamim",
	"Tawid",
	"Zahiri",
	"Milad",
	"Nuh",
	"Abdari",
	"Junaid",
	"Malik",
	"Naser",
	"Jahaf",
	"Yazir",
	"Talha",
	"Sabti",
	"Harun",
	"Firi",
	"Rashid",
	"Hamdin",
	"Rasil",
	"Hayan",
	"Askari",
	"Barkud",
	"Husni",
	"Omar"
];
gt.Const.Strings.SouthernNamesLast <- [
	"Ibn Sahr",
	"Al-Dani",
	"Ibn Tayib",
	"Al-Sahl",
	"Ibn Hazam",
	"Ibn Jalaf",
	"Ibn Abbad",
	"Al-Tahir",
	"Al-Bajani",
	"Ibn Nusa",
	"Al-Faris",
	"Al-Wahiri",
	"Ibn Nuh",
	"Al-Kasim",
	"Ibn Husain",
	"Ibn Kamal",
	"Al-Fad",
	"Al-Baji",
	"Al-Aban",
	"Al-Salama",
	"Al-Haddad",
	"Al-Affan",
	"Al-Bakr",
	"Ibn Tasuf",
	"Al-Faradi",
	"Ibn Tayib",
	"Ibn Azid",
	"Ibn Wasi",
	"Al-Abbas",
	"Ibn Hamdi",
	"Al-Bahri",
	"Al-Zahir",
	"Ibn Salar",
	"Al-Sawid",
	"Ibn Hamdin",
	"Ibn Undi",
	"Ibn Asili",
	"Al-Tabar",
	"Al-Rundi",
	"Al-Siddiq",
	"Ibn Sabti",
	"Al-Fath",
	"Ibn Mansur",
	"Al-Sabbag",
	"Al-Benali",
	"Al-Aziz",
	"Ibn Jasib"
];
gt.Const.Strings.SouthernOfficerTitles <- [
	"Al-Jawlan",
	"Al-Talamanki",
	"Al-Mundir",
	"Al-Jasur Ibn Tawd",
	"Al-Jatami",
	"Al-Harun",
	"Al-Badir",
	"Al-Mayuriqi",
	"Al-Muharib",
	"Al-Tarabulusi Ibn-Asbat",
	"Al-Tasufin Ibn Habib",
	"Ibn Zayid",
	"Ibn Asmali",
	"Ibn Ibrahim",
	"Ibn Suhaliy"
];
gt.Const.Strings.GladiatorTitles <- [
	"the Pit Fighter",
	"the Arena King",
	"the Merciless",
	"the Head-Taker",
	"the Unmatched",
	"the Undefeated",
	"the Brutalizer",
	"the Underdog",
	"the Slave",
	"the Lion",
	"the Hyena",
	"the Victorious",
	"the Volunteer",
	"the Butcher",
	"the Champion",
	"the Gladiator",
	"the Stallion",
	"the Beast",
	"the Marvelous",
	"the Raging Bull",
	"the Thunder",
	"Steelhammer",
	"the Destroyer",
	"the Impaler"
];
gt.Const.Strings.NomadChampionTitles <- [
	"the Scorpion",
	"the Ghost of the Sands",
	"the Serpent",
	"the Blight",
	"the Silver Mace",
	"the Desert Prince",
	"the Elusive",
	"the Shadow",
	"the Plunderer",
	"the Robber",
	"the Nomad King",
	"the Thief of the Sands",
	"the Traders\' Bane",
	"the Desert Rat",
	"the Black Fang",
	"the Snake",
	"the Desert Raider",
	"the Scourge",
	"the Cursed",
	"the Raven",
	"the Nomad",
	"the Red",
	"the Gilder\'s Chosen",
	"the Sandviper",
	"the Pilgrim",
	"the Exiled",
	"the Vulture",
	"the Living Mirage",
	"the Free Prince",
	"the Prince of the Sands",
	"the Dust Dancer",
	"the Golden Vulture"
];
gt.Const.Strings.NomadChampionStandalone <- [
	"The Scorpion",
	"The Ghost of the Sands",
	"The Serpent",
	"The Blight",
	"The Silver Mace",
	"The Desert Prince",
	"The Elusive",
	"The Shadow",
	"The Plunderer",
	"The Robber",
	"The Nomad King",
	"The Thief of the Sands",
	"The Traders\' Bane",
	"The Desert Rat",
	"The Black Fang",
	"The Snake",
	"The Desert Raider",
	"The Scourge",
	"The Cursed",
	"The Raven",
	"The Nomad",
	"The Red",
	"The Exiled",
	"The Vulture",
	"The Living Mirage",
	"The Free Prince",
	"The Prince of the Sands",
	"The Dust Dancer",
	"The Golden Vulture"
];
gt.Const.Strings.DesertDevilChampionTitles <- [
	"The Scorpion",
	"The Ghost of the Sands",
	"%randomsouthernname% the Viper",
	"%randomsouthernname% the Blademaster",
	"%randomsouthernname% the Desert Devil",
	"%randomsouthernname% the Elusive",
	"%randomsouthernname% the Shadow",
	"%randomsouthernname% the Snake",
	"The Whirlwind",
	"The Sand Devil",
	"%randomsouthernname% the Sandviper",
	"%randomsouthernname% the Exiled",
	"%randomsouthernname% the Blade Dancer",
	"%randomsouthernname% the Swift",
	"%randomsouthernname% the Undefeated",
	"%randomsouthernname% the Dust Dancer",
	"%randomsouthernname% the Glistening Edge",
	"%randomsouthernname% the Crimson Edge",
	"%randomsouthernname% the Flying Blade",
	"%randomsouthernname% the Dust Devil",
	"The Striking Wind",
	"The Black Hawk"
];
gt.Const.Strings.ExecutionerChampionTitles <- [
	"The Executioner",
	"The Silver Mace",
	"The Plunderer",
	"The Traders\' Bane",
	"The Scourge",
	"The Cursed",
	"The Sand Giant",
	"The Gilder\'s Chosen",
	"The Mountain",
	"The Scimitar",
	"%randomsouthernname% the Gilded",
	"The Raging Nomad",
	"%randomsouthernname% the Immortal",
	"The Headcollector",
	"The Giant",
	"The Rock",
	"The Sandstorm",
	"The Headcrusher",
	"The Ifrit",
	"%randomsouthernname% the Lion"
];
gt.Const.Strings.DesertStalkerChampionTitles <- [
	"the Scorpion",
	"the Sand Stalker",
	"the Desert Stalker",
	"the Eagle",
	"the Raven",
	"the Hawk",
	"the Deathstalker",
	"the Master Archer",
	"the Hunter",
	"the Headhunter",
	"the Sandviper",
	"the Ray of Light",
	"the Gilders\' Hand",
	"Eye of the Hawk",
	"the Vulture",
	"the Serpent",
	"the Stinger",
	"the Heartseeker"
];
gt.Const.Strings.NobleTitles <- [
	"Count",
	"Count",
	"Baron",
	"Baron",
	"Duke"
];
gt.Const.Strings.VizierTitles <- [
	"the Vizier of War",
	"the Vizier of Treasury",
	"the Vizier of Trade",
	"the Grand Vizier",
	"the Master Astrologer",
	"the High Priest"
];
gt.Const.Strings.SellswordTitles <- [
	"the Butcher",
	"the Berserker",
	"the Dog",
	"the Hound",
	"the Bloody",
	"the Wolf",
	"the Blade",
	"the Impaler",
	"the Younger",
	"the Older",
	"the Merciless",
	"the Red",
	"the Black",
	"Orcbane",
	"the Knightslayer",
	"the Falcon"
];
gt.Const.Strings.SwordmasterTitles <- [
	"the Legend",
	"the Master",
	"the Fencer",
	"the Fast",
	"Quickblade",
	"the Serpent",
	"the Swift",
	"Bladedancer",
	"the Undefeated",
	"the Unbeaten",
	"the Champion",
	"the Master of the Realm",
	"the Elder",
	"the Unmatched",
	"the Skillful",
	"the Flying Blade",
	"the Dancing Blade"
];
gt.Const.Strings.HedgeKnightTitles <- [
	"The Lone Wolf",
	"The Wolf",
	"The Hound",
	"Steelwielder",
	"The Slayer",
	"The Giant",
	"The Mountain",
	"The Defiler",
	"The Knightslayer",
	"The Hedge Knight",
	"The Scourge",
	"The Fallen Knight",
	"Mancrusher",
	"The Exiled",
	"Warshout",
	"The Skulltaker",
	"The Cleaver"
];
gt.Const.Strings.MasterArcherNames <- [
	"%randomname% the Marksman",
	"Sureshot",
	"%randomname% the Master Archer",
	"%randomname% the Hunter",
	"%randomname% the Sniper",
	"Hundred Paces",
	"%randomname% Quick Shot",
	"%randomname% the Headhunter",
	"Deadeye",
	"%randomname% the Sharpshooter",
	"%randomname% the Shooter",
	"%randomname% Featherdraw",
	"%randomname% the Whistling Death",
	"%randomname% the Poker",
	"The Eagle",
	"%randomname% Truestrike",
	"%randomname% the True Shot"
];
gt.Const.Strings.OathbringerNames <- [
	"The Oathkeeper",
	"%randomname% the Oathbringer",
	"Anselm\'s Hammer",
	"Anselm\'s Shield",
	"Anselm\'s Sword",
	"Anselm\'s Stolen Valor",
	"%randomname% the Oathsworn",
	"%randomname% the Crusader",
	"%randomname% the Zealot",
	"%randomname% the Pious",
	"%randomname% the Devoted",
	"%randomname% the Paladin",
	"%randomname% the Righteous"
];
gt.Const.Strings.MasonTitles <- [
	"the Builder",
	"Bricklayer",
	"the Architect",
	"the Artisan"
];
gt.Const.Strings.MilitiaTitles <- [
	"the Conscript",
	"the Militiaman",
	"the Footman"
];
gt.Const.Strings.BrawlerTitles <- [
	"Hamfisted",
	"the Mauler",
	"the Rock",
	"the Stallion",
	"Ironjaw",
	"the Brawler"
];
gt.Const.Strings.PeddlerTitles <- [
	"the Snake",
	"the Weasel",
	"Silver-Tongue",
	"the Sutler",
	"the Peddler",
	"the Merchant"
];
gt.Const.Strings.WitchhunterTitles <- [
	"the Nighthunter",
	"the Witchhunter",
	"the Exorciser",
	"the Torturer"
];
gt.Const.Strings.GravediggerTitles <- [
	"the Gravedigger",
	"the Shoveler",
	"Gravespotter",
	"the Odd"
];
gt.Const.Strings.RatcatcherTitles <- [
	"Longnose",
	"the Rat",
	"the Ratcatcher",
	"the Tepid"
];
gt.Const.Strings.BastardTitles <- [
	"the Bastard",
	"the Mistake",
	"Cuckchild",
	"the Secret Son",
	"Whoreson",
	"the Tarnish"
];
gt.Const.Strings.PilgrimTitles <- [
	"the Believer",
	"the Seeker",
	"the Thaumaturge",
	"the Pure",
	"the Flagellant",
	"the Pilgrim"
];
gt.Const.Strings.KnightNames <- [
	"Sir Roderick",
	"Sir Egidius",
	"Sir Henrik",
	"Sir Dankwart",
	"Sir Eisenherz",
	"Sir Geofram",
	"Sir Baranor",
	"Sir Wilhelm",
	"Sir Hildebrand",
	"Sir Hilmar",
	"Sir Severin",
	"Sir Starkwart",
	"Sir Elgast",
	"Sir Magnus",
	"Sir Burkhard",
	"Sir Silvan",
	"Sir Lambert",
	"Sir Kuno",
	"Sir Wenzel",
	"Sir Donatus",
	"Sir Albrecht",
	"Sir Hilderich",
	"Sir Sigmund",
	"Sir Steinhart",
	"Sir Hermann",
	"Sir Eckhart",
	"Sir Guidobald",
	"Sir Theo",
	"Sir Eswig",
	"Sir Walram",
	"Sir Casimir",
	"Sir Magnus",
	"Sir Wighart",
	"Sir Otto",
	"Sir Sigismund",
	"Sir Erland",
	"Sir Erkenbrand",
	"Sir Theoderich",
	"Sir Lothar",
	"Sir Wolfhart",
	"Sir Balon",
	"Sir Valdemar",
	"Sir Giselherr",
	"Sir Engelbert",
	"Sir Lancel",
	"Sir Humbert",
	"Sir Emmerich",
	"Sir Grimm",
	"Sir Donbert",
	"Sir Robert",
	"Sir Wolfgang",
	"Sir Kettilmund",
	"Sir Konrad",
	"Sir Rupert",
	"Sir Harald",
	"Sir Roland",
	"Sir Rabe",
	"Sir Siegfried",
	"Sir Kunibert",
	"Sir Dankrad",
	"Sir Leberecht"
];
gt.Const.Strings.OrcWarlordNames <- [
	"Illska Ghul",
	"Skabskra",
	"Urosh",
	"Kushtrum",
	"Goth Na Ari",
	"Obrokk",
	"Blok Sapat",
	"Gorash",
	"Mogtul",
	"Thraktar",
	"Gorgash-Ghul",
	"Maruk",
	"Warak Na Borash",
	"Urgat",
	"Durgash",
	"Skalleklyfta",
	"Margash Borash",
	"Borgash",
	"Goruk Sapat",
	"Karosh Urgat",
	"Horgash Ghul",
	"Naguk",
	"Shadok",
	"Bakh Lob",
	"Corgat",
	"Urmuk Ghul",
	"Mug Nadar",
	"Vras Ushtar",
	"Brulk Zogtar",
	"Sapat Blok",
	"Mosh Shagit",
	"Gajit Bukol",
	"Blot Kakok",
	"Thrak Talun",
	"Drod Kazan",
	"Oxshak",
	"Urdanog",
	"Trok Oborr",
	"Bolvag Shrub",
	"Ug Shatup",
	"Shatratog",
	"Buruk Skag",
	"Ilska Sapat",
	"Grug Zartum",
	"Grommok",
	"Ogrul",
	"Shura Nak"
];
gt.Const.Strings.BanditLeaderNames <- [
	"The Butcher",
	"%randomname% the Knife",
	"%randomname% the Slaughterer",
	"King %randomname%",
	"%randomname% the Ox",
	"The Wolf",
	"%randomname% the Marauder",
	"%randomname% the Snake",
	"%randomname% Four Fingers",
	"Barabas Brimstone",
	"Rotor Ravensblack",
	"Black Crow Balthasar",
	"The Bull of %randomtown%",
	"%randomname% Bloodbeard",
	"Mead Jar %randomname%",
	"Bloody %randomname%",
	"Dreaded %randomname%",
	"The Swine",
	"%randomname% the Cruel",
	"%randomname% the Outcast",
	"The Robber Baron",
	"Red Viper",
	"%randomname% the Brigand",
	"%randomname% the Scourge",
	"The Raiding Lord",
	"The Manhunter",
	"Big %randomname%",
	"%randomname% the Savage",
	"Infamous %randomname%",
	"The Menace of %randomtown%",
	"%randomname% the Red",
	"Gunther the Grinning",
	"%randomname% the Hyena",
	"%randomname% the Hawk",
	"%randomname% the Mad",
	"%randomname% the Brute",
	"%randomname% the Pillager",
	"Lars the Lunatic",
	"%randomname% the Free",
	"Black Eyes Einhart",
	"Oswall the Odd",
	"Brokk Mad Eyes",
	"%randomname% the Ashen Prince",
	"The Scourge of %randomtown%",
	"%randomname% the Bleak",
	"Bleak Blade Ingram",
	"%randomname% the Pickpocket",
	"Mickel Copperheart",
	"Casper the Cutpurse",
	"Ottel Bleakheart",
	"Joost Crowntaker",
	"Baltasar the Toothless",
	"Walter the Spider",
	"August the Gravedigger",
	"Urban Goodman"
];
gt.Const.Strings.KrakenNames <- [
	"Ogg-Sattoth the Grand Devourer",
	"Kha-Athlu the All-Ender",
	"Shaggaruth the Unending",
	"Gla-Oth the Endless Maw",
	"Gu-Shogg the Thousand-Armed Thresher",
	"Chtan-Nahitil the Gorger of All",
	"Xa-Shutar the Eater of Worlds",
	"Thohochoth the All-Ender",
	"Naccorath the Eternal",
	"Xapocathlu the All-Reaching"
];
gt.Const.Strings.AncientDeadNames <- [
	"Brasus",
	"Gudila",
	"Ostracon",
	"Dardanos",
	"Duras",
	"Mucatra",
	"Cothelas",
	"Arzaru",
	"Decalus",
	"Akamas",
	"Kavaros",
	"Comoscius",
	"Moskon",
	"Rholes",
	"Tarbus",
	"Apulon",
	"Napucon",
	"Barsobis",
	"Sirus",
	"Marnis",
	"Burrus",
	"Telephos",
	"Terebus",
	"Damastes",
	"Megerus",
	"Ianoton",
	"Cyrenos",
	"Haganon",
	"Neritos",
	"Seleukus",
	"Nomion",
	"Bacenor",
	"Caston",
	"Elpidus",
	"Aristes",
	"Morsimus",
	"Athenades",
	"Bacius"
];
gt.Const.Strings.AncientDeadTitles <- [
	"the Returned",
	"the Restorator",
	"the Ancient",
	"the Destroyer",
	"the Guardian",
	"the Hunter",
	"the Second",
	"the Herald",
	"the Unearthed",
	"the Forgotten",
	"the Protector",
	"the Honored",
	"the Defender",
	"of the North",
	"the Glorious",
	"the Favored"
];
gt.Const.Strings.GoblinNames <- [
	"Nox",
	"Grubb",
	"Sharax",
	"Zuggut",
	"Grisnik",
	"Zatak",
	"Finex",
	"Zugtakr",
	"Velok",
	"Zatox",
	"Naxanix",
	"Vlixix",
	"Snarf",
	"Ratox",
	"Skrork",
	"Wruzak",
	"Drozub",
	"Zogrok",
	"Kulzik",
	"Xatox",
	"Vekuz",
	"Carax",
	"Drukzug",
	"Xeegox",
	"Sruzuz",
	"Drutnog",
	"Nogzak",
	"Wreek",
	"Zatush",
	"Kleklux"
];
gt.Const.Strings.GoblinTitles <- [
	"the Stabber",
	"the Insidious",
	"Throatcutter",
	"Knifelicker",
	"the Skinner",
	"the Headhunter",
	"Eyegouger",
	"Rotgut",
	"Longnose",
	"the Cutter",
	"Nosebiter",
	"the Sticker",
	"the Elusive",
	"the Stalker",
	"the Shadowwalker",
	"the Fogwalker",
	"the Cunning",
	"the Backstabber",
	"Hooked Blade",
	"Gutstabber",
	"Earripper",
	"Necksnapper",
	"the Knifejuggler"
];
gt.Const.Strings.FallenHeroTitles <- [
	"the Decayed",
	"the Unburied",
	"the Rotten",
	"the Defiled",
	"the Returned",
	"the Undying",
	"the Cursed",
	"the Corrupted",
	"the Unbreakable",
	"the Oathbreaker",
	"the Forgotten",
	"the Lost",
	"the Fallen Hero",
	"the Cruel",
	"the Returned",
	"the Prince of Rot",
	"the Hollow",
	"the Ghost",
	"the Soulless",
	"the Vessel"
];
gt.Const.Strings.NecromancerNames <- [
	"King of Worms",
	"%randomname% the Undying",
	"%randomname% the Black",
	"%randomname% the Necromancer",
	"The Puppeteer",
	"The Plaguebringer",
	"The Dark Master",
	"The Reanimator",
	"%randomname% the Mad",
	"%randomname% the Obsessed",
	"The Pale Duke",
	"The Master of Undeath",
	"%randomname% the Apostate",
	"%randomname% the Knowledgeable",
	"%randomname% the Wormbitten",
	"%randomname% the Unholy",
	"%randomname% the Mad",
	"%randomname% the Enlightened"
];

